
openapi: '3.0.2'
info:
  title: Formula Bun API
  version: '1.0'
servers:
  - url: https://api.formulabun.club/


components:
  schemas:
    link:
      title: Link
      type: object
      properties:
        links:
          type: array
          items:
            type: object
            properties:
              rel:
                type: string
                example: discord
              url:
                type: string
                example: http://api.formulabun.club/discord
paths:
  /:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/link'
  /servers:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  links:
                    type: array
                    items:
                      $ref: '#/components/schemas/link'
  /servers/{server}:
    get:
      responses:
        '200':
          description: OK
  /servers/{server}/players:
    get:
      responses:
        '200':
          description: OK
  /servers/{server}/server:
    get:
      responses:
        '200':
          description: OK
  /discord:
    get:
      responses:
        '200':
          description: OK
