
openapi: '3.0.2'
info:
  title: Formula Bun API
  version: '1.0'
servers:
  - url: https://api.formulabun.club/
paths:
  /:
    get:
      responses:
        '200':
          description: OK
  /servers:
    get:
      responses:
        '200':
          description: OK
  /servers/{server}:
    get:
      responses:
        '200':
          description: OK
  /servers/{server}/players:
    get:
      responses:
        '200':
          description: OK
  /servers/{server}/server:
    get:
      responses:
        '200':
          description: OK
  /discord:
    get:
      responses:
        '200':
          description: OK
